export const themeWarm = {
  base: {
    'font-family': 'PingFangSC-Regular',
    'font-size': '12px',
    'background-color': '#fffaf5',
  },
  input: {
    's-i-w-padding': '.6em',
    's-i-w-bg': '#ffffff',
    's-i-w-border-radius': '1em',
    's-i-w-box-shadow': '0px 5px 12px 2px rgba(255, 152, 0, 0.12)',
    's-i-w-border-width': '1px',
    's-i-w-border-color': '#ffb366',
    's-i-height': '2.25em',
    's-i-color': '#5a3d1c',
    's-i-line-height': '1.25em',
    's-i-font-size': '.875em',
    's-i-padding': '.5em 4em .5em 1.5em',
    's-p-d-bg-image': 'url(../../assets/send-default-warm.svg)',
    's-p-a-bg-image': 'url(../../assets/send-can-warm.svg)',
    's-b-pending-background-bg': 'rgba(255, 140, 0, 0.15)',
    's-b-pending-background-width': '2em',
    's-b-pending-background-height': '2em',
    's-b-pending-bg': 'linear-gradient(90deg, #ff9a3d 0%, #ff6f00 100%)',
    's-b-pending-width': '2em',
    's-b-pending-height': '2em',
    's-b-pending-inner-width': '.6em',
    's-b-pending-inner-height': '.6em',
  },
  conversation: {
    's-width': '240px',
    's-padding': '8px 20px',
    's-background-color': '#fff3e0',
    's-n-width': '200px',
    's-n-height': '40px',
    's-n-padding': '6px 10px',
    's-n-margin': '20px auto',
    's-n-border-radius': '12px',
    'i-padding': '0.5rem',
    'i-border-radius': '0.5rem',
    'i-n-max-width': '160px',
    'i-n-line-height': '24px',
    'i-a-color': '#4e342e',
    'i-a-box-shadow': '0 5px 10px 1px rgba(255, 152, 0, 0.1)',
    'i-a-background-color': 'rgba(255, 152, 0, 0.06)',
    'i-background-color-hover': 'rgba(255, 152, 0, 0.04)',
  },
  bubble: {
    'b-c-padding': '10px 16px',
    'b-c-background-color': '#ffe0b2',
    'b-c-border-radius': '16px',
  },
  welcome: {
    'w-b-radius': '0.8em',
    'w-background': 'linear-gradient(135deg, #ffe0b2 0%, #ffcc80 100%)',
    'w-padding': '1.25em',
    'w-margin': '1em',
    'w-width': 'calc(100% - 2em)',
    'w-t-color': '#5a3d1c',
    'w-t-font-weight': 'bold',
    'w-t-font-size': '18px',
    'w-t-line-height': '26px',
    'w-t-margin-bottom': '8px',
    'w-d-color': '#7a542c',
    'w-d-font-weight': '600',
    'w-d-font-size': '14px',
    'w-d-line-height': 'normal',
    'w-d-margin-bottom': '14px',
    'w-p-t-color': '#a9824f',
    'w-p-t-font-weight': 'regular',
    'w-p-t-font-size': '12px',
    'w-p-t-line-height': '18px',
    'w-p-t-margin-bottom': '8px',
    'w-p-i-border-radius': '6px',
    'w-p-i-background': '#ffffff',
    'w-p-i-color': '#7a542c',
    'w-p-i-font-weight': 'regular',
    'w-p-i-font-size': '14px',
    'w-p-i-line-height': '20px',
    'w-p-i-padding': '10px 12px',
    'w-p-i-margin-bottom': '12px',
    'w-p-i-hover-background': '#fff8f0',
  },
  header: {
    width: '100%',
    height: '4em',
    bg: '#ff9800',
    color: '#ffffff',
    'font-size': '1.5em',
  },
};
