export const themeDark = {
  base: {
    'font-family': 'PingFangSC-Regular',
    'font-size': '12px',
    'background-color': '#1a1a1a',
  },
  input: {
    's-i-w-padding': '.6em',
    's-i-w-bg': 'rgb(30, 30, 30)',
    's-i-w-border-radius': '.5em',
    's-i-w-box-shadow': '0px 5px 10px 1px rgba(0, 0, 0, 0.5)',
    's-i-w-border-width': '1px',
    's-i-w-border-color': 'rgba(90, 90, 90, 1)',
    's-i-height': '2.25em',
    's-i-color': 'rgba(220, 220, 220, 1)',
    's-i-line-height': '1.25em',
    's-i-font-size': '.875em',
    's-i-padding': '.5em 4em .5em 1.5em',
    's-p-d-bg-image': 'url(../../assets/send-default-dark.svg)',
    's-p-a-bg-image': 'url(../../assets/send-can-dark.svg)',
    's-b-pending-background-bg': 'rgba(90, 90, 90, 0.2)',
    's-b-pending-background-width': '2em',
    's-b-pending-background-height': '2em',
    's-b-pending-bg':
      'linear-gradient(90.00deg, rgb(70, 70, 70), rgb(40, 40, 40) 100%)',
    's-b-pending-width': '2em',
    's-b-pending-height': '2em',
    's-b-pending-inner-width': '.6em',
    's-b-pending-inner-height': '.6em',
  },
  conversation: {
    's-width': '240px',
    's-padding': '8px 20px',
    's-background-color': '#262626',
    's-n-width': '200px',
    's-n-height': '40px',
    's-n-padding': '6px 10px',
    's-n-margin': '20px auto',
    's-n-border-radius': '10px',
    'i-padding': '0.5rem',
    'i-border-radius': '0.375rem',
    'i-n-max-width': '160px',
    'i-n-line-height': '24px',
    'i-a-color': 'rgba(255, 255, 255, .9)',
    'i-a-box-shadow': '0 5px 10px 1px #00000019',
    'i-a-background-color': 'rgba(255, 255, 255, .05)',
    'i-background-color-hover': 'rgba(255, 255, 255, .03)',
  },
  bubble: {
    'b-c-padding': '10px 16px',
    'b-c-background-color': '#333333',
    'b-c-border-radius': '12px',
  },
  welcome: {
    'w-b-radius': '0.5em',
    'w-background': 'linear-gradient(122.16deg, #2c2c2c 0%, #1a1a1a 100%)',
    'w-padding': '1.25em',
    'w-margin': '1em',
    'w-width': 'calc(100% - 2em)',
    'w-t-color': '#ffffff',
    'w-t-font-weight': 'bold',
    'w-t-font-size': '18px',
    'w-t-line-height': '26px',
    'w-t-margin-bottom': '8px',
    'w-d-color': '#cccccc',
    'w-d-font-weight': '600',
    'w-d-font-size': '14px',
    'w-d-line-height': 'normal',
    'w-d-margin-bottom': '14px',
    'w-p-t-color': '#999999',
    'w-p-t-font-weight': 'regular',
    'w-p-t-font-size': '12px',
    'w-p-t-line-height': '18px',
    'w-p-t-margin-bottom': '8px',
    'w-p-i-border-radius': '4px',
    'w-p-i-background': '#1a1a1a',
    'w-p-i-color': '#cccccc',
    'w-p-i-font-weight': 'regular',
    'w-p-i-font-size': '14px',
    'w-p-i-line-height': '20px',
    'w-p-i-padding': '10px 12px',
    'w-p-i-margin-bottom': '12px',
    'w-p-i-hover-background': '#0d0d0d',
  },
  header: {
    width: '100%',
    height: '4em',
    bg: '#000000',
    color: '#ffffff',
    'font-size': '1.5em',
  },
};
