export default {
  'w-b-radius': '0.5em',
  'w-background': 'linear-gradient(122.16deg, #f1e7fc 0%, #cfe3ff 100%)',
  'w-padding': '1.25em',
  'w-margin': '1em',
  'w-width': 'calc(100% - 2em)',
  'w-t-color': '#111111',
  'w-t-font-weight': 'bold',
  'w-t-font-size': '18px',
  'w-t-line-height': '26px',
  'w-t-margin-bottom': '8px',
  'w-d-color': '#333',
  'w-d-font-weight': '600',
  'w-d-font-size': '14px',
  'w-d-line-height': 'normal',
  'w-d-margin-bottom': '14px',
  'w-p-t-color': '#666',
  'w-p-t-font-weight': 'regular',
  'w-p-t-font-size': '12px',
  'w-p-t-line-height': '18px',
  'w-p-t-margin-bottom': '8px',
  'w-p-i-border-radius': '4px',
  'w-p-i-background': '#fff',
  'w-p-i-color': '#333',
  'w-p-i-font-weight': 'regular',
  'w-p-i-font-size': '14px',
  'w-p-i-line-height': '20px',
  'w-p-i-padding': '10px 12px',
  'w-p-i-margin-bottom': '12px',
  'w-p-i-hover-background': '#f6f7f8',
}


